#!/usr/bin/env sh

# This script creates multiple Django apps in the specified apps directory using the 'django-admin startapp' command.

# Function to handle the creation of multiple apps
startapp() {
    local app_names="$@"

    # Check if required arguments are provided
    if [[ $# -eq 0 ]]; then
        message_error "Usage: $0 <app names separated by space>"
        exit 1
    fi

    for app_name in $app_names; do
        mkdir -p "${APPS_DIRECTORY}/${app_name}" && django-admin startapp ${app_name} "${APPS_DIRECTORY}/${app_name}"
        if [ $? -eq 0 ]; then
            message_success "The app '${app_name}' has been created successfully."
        fi
    done
}

# Call the startapp function with the provided arguments
startapp "$@"
