#!/usr/bin/env sh

# Set the DATABASE_URL environment variable using the provided PostgreSQL connection details
export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"

exec "$@"
