#!/usr/bin/env sh

# Exit script immediately if a command fails
set -o errexit
# Exit script if it tries to use unset variables
set -o nounset

# Define the project and workdir directory
workdir="$(cd "$(dirname "$0")" && pwd)" # Directory of the script
project_dir=$(realpath "$workdir")       # Project directory

# Source necessary files
source "${workdir}/sources/_constants.sh" # Constants file
source "${workdir}/sources/_messages.sh"  # Messages file
source "${workdir}/sources/_utils.sh"     # Utilities file

# Use watchmedo to monitor changes in Python files in the /app/config directory and restart the celery worker if changes occur
watchmedo auto-restart -d config/ -p '*.py' -- celery -A config worker --loglevel=info
